# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies and build app
RUN npm install --ignore-scripts

# Copy remaining source files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional) 
# EXPOSE 4100

# Start the server
CMD ["node", "build/index.js"]
